on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish PlatformIO package
    steps:

      - uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-python@v4
        
      - name: Install PlatformIO
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: update release version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          cicd/bump-version.sh

      - name: Publish package
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: platformio pkg publish --no-interactive
